# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Produce verbose output by default.
VERBOSE = 1

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/robin/workspace/Project_Hochschule/Embedded

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/robin/workspace/Project_Hochschule/Embedded

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/robin/workspace/Project_Hochschule/Embedded/CMakeFiles /home/robin/workspace/Project_Hochschule/Embedded/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/robin/workspace/Project_Hochschule/Embedded/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named HELIKOPTER

# Build rule for target.
HELIKOPTER: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 HELIKOPTER
.PHONY : HELIKOPTER

# fast build rule for target.
HELIKOPTER/fast:
	$(MAKE) -f CMakeFiles/HELIKOPTER.dir/build.make CMakeFiles/HELIKOPTER.dir/build
.PHONY : HELIKOPTER/fast

#=============================================================================
# Target rules for targets named communication

# Build rule for target.
communication: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 communication
.PHONY : communication

# fast build rule for target.
communication/fast:
	$(MAKE) -f CMakeFiles/communication.dir/build.make CMakeFiles/communication.dir/build
.PHONY : communication/fast

#=============================================================================
# Target rules for targets named sensor

# Build rule for target.
sensor: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sensor
.PHONY : sensor

# fast build rule for target.
sensor/fast:
	$(MAKE) -f CMakeFiles/sensor.dir/build.make CMakeFiles/sensor.dir/build
.PHONY : sensor/fast

#=============================================================================
# Target rules for targets named motor

# Build rule for target.
motor: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 motor
.PHONY : motor

# fast build rule for target.
motor/fast:
	$(MAKE) -f CMakeFiles/motor.dir/build.make CMakeFiles/motor.dir/build
.PHONY : motor/fast

#=============================================================================
# Target rules for targets named lld

# Build rule for target.
lld: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lld
.PHONY : lld

# fast build rule for target.
lld/fast:
	$(MAKE) -f CMakeFiles/lld.dir/build.make CMakeFiles/lld.dir/build
.PHONY : lld/fast

#=============================================================================
# Target rules for targets named sig

# Build rule for target.
sig: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sig
.PHONY : sig

# fast build rule for target.
sig/fast:
	$(MAKE) -f CMakeFiles/sig.dir/build.make CMakeFiles/sig.dir/build
.PHONY : sig/fast

helikopter-src/hal/HAL_LIB/GPIO.o: helikopter-src/hal/HAL_LIB/GPIO.c.o

.PHONY : helikopter-src/hal/HAL_LIB/GPIO.o

# target to build an object file
helikopter-src/hal/HAL_LIB/GPIO.c.o:
	$(MAKE) -f CMakeFiles/communication.dir/build.make CMakeFiles/communication.dir/helikopter-src/hal/HAL_LIB/GPIO.c.o
.PHONY : helikopter-src/hal/HAL_LIB/GPIO.c.o

helikopter-src/hal/HAL_LIB/GPIO.i: helikopter-src/hal/HAL_LIB/GPIO.c.i

.PHONY : helikopter-src/hal/HAL_LIB/GPIO.i

# target to preprocess a source file
helikopter-src/hal/HAL_LIB/GPIO.c.i:
	$(MAKE) -f CMakeFiles/communication.dir/build.make CMakeFiles/communication.dir/helikopter-src/hal/HAL_LIB/GPIO.c.i
.PHONY : helikopter-src/hal/HAL_LIB/GPIO.c.i

helikopter-src/hal/HAL_LIB/GPIO.s: helikopter-src/hal/HAL_LIB/GPIO.c.s

.PHONY : helikopter-src/hal/HAL_LIB/GPIO.s

# target to generate assembly for a file
helikopter-src/hal/HAL_LIB/GPIO.c.s:
	$(MAKE) -f CMakeFiles/communication.dir/build.make CMakeFiles/communication.dir/helikopter-src/hal/HAL_LIB/GPIO.c.s
.PHONY : helikopter-src/hal/HAL_LIB/GPIO.c.s

helikopter-src/hal/HAL_LIB/HAL_ADC.o: helikopter-src/hal/HAL_LIB/HAL_ADC.c.o

.PHONY : helikopter-src/hal/HAL_LIB/HAL_ADC.o

# target to build an object file
helikopter-src/hal/HAL_LIB/HAL_ADC.c.o:
	$(MAKE) -f CMakeFiles/communication.dir/build.make CMakeFiles/communication.dir/helikopter-src/hal/HAL_LIB/HAL_ADC.c.o
.PHONY : helikopter-src/hal/HAL_LIB/HAL_ADC.c.o

helikopter-src/hal/HAL_LIB/HAL_ADC.i: helikopter-src/hal/HAL_LIB/HAL_ADC.c.i

.PHONY : helikopter-src/hal/HAL_LIB/HAL_ADC.i

# target to preprocess a source file
helikopter-src/hal/HAL_LIB/HAL_ADC.c.i:
	$(MAKE) -f CMakeFiles/communication.dir/build.make CMakeFiles/communication.dir/helikopter-src/hal/HAL_LIB/HAL_ADC.c.i
.PHONY : helikopter-src/hal/HAL_LIB/HAL_ADC.c.i

helikopter-src/hal/HAL_LIB/HAL_ADC.s: helikopter-src/hal/HAL_LIB/HAL_ADC.c.s

.PHONY : helikopter-src/hal/HAL_LIB/HAL_ADC.s

# target to generate assembly for a file
helikopter-src/hal/HAL_LIB/HAL_ADC.c.s:
	$(MAKE) -f CMakeFiles/communication.dir/build.make CMakeFiles/communication.dir/helikopter-src/hal/HAL_LIB/HAL_ADC.c.s
.PHONY : helikopter-src/hal/HAL_LIB/HAL_ADC.c.s

helikopter-src/hal/HAL_LIB/udpLib.o: helikopter-src/hal/HAL_LIB/udpLib.c.o

.PHONY : helikopter-src/hal/HAL_LIB/udpLib.o

# target to build an object file
helikopter-src/hal/HAL_LIB/udpLib.c.o:
	$(MAKE) -f CMakeFiles/communication.dir/build.make CMakeFiles/communication.dir/helikopter-src/hal/HAL_LIB/udpLib.c.o
.PHONY : helikopter-src/hal/HAL_LIB/udpLib.c.o

helikopter-src/hal/HAL_LIB/udpLib.i: helikopter-src/hal/HAL_LIB/udpLib.c.i

.PHONY : helikopter-src/hal/HAL_LIB/udpLib.i

# target to preprocess a source file
helikopter-src/hal/HAL_LIB/udpLib.c.i:
	$(MAKE) -f CMakeFiles/communication.dir/build.make CMakeFiles/communication.dir/helikopter-src/hal/HAL_LIB/udpLib.c.i
.PHONY : helikopter-src/hal/HAL_LIB/udpLib.c.i

helikopter-src/hal/HAL_LIB/udpLib.s: helikopter-src/hal/HAL_LIB/udpLib.c.s

.PHONY : helikopter-src/hal/HAL_LIB/udpLib.s

# target to generate assembly for a file
helikopter-src/hal/HAL_LIB/udpLib.c.s:
	$(MAKE) -f CMakeFiles/communication.dir/build.make CMakeFiles/communication.dir/helikopter-src/hal/HAL_LIB/udpLib.c.s
.PHONY : helikopter-src/hal/HAL_LIB/udpLib.c.s

helikopter-src/hal/HAL_LIB/udpSensorLib.o: helikopter-src/hal/HAL_LIB/udpSensorLib.c.o

.PHONY : helikopter-src/hal/HAL_LIB/udpSensorLib.o

# target to build an object file
helikopter-src/hal/HAL_LIB/udpSensorLib.c.o:
	$(MAKE) -f CMakeFiles/communication.dir/build.make CMakeFiles/communication.dir/helikopter-src/hal/HAL_LIB/udpSensorLib.c.o
.PHONY : helikopter-src/hal/HAL_LIB/udpSensorLib.c.o

helikopter-src/hal/HAL_LIB/udpSensorLib.i: helikopter-src/hal/HAL_LIB/udpSensorLib.c.i

.PHONY : helikopter-src/hal/HAL_LIB/udpSensorLib.i

# target to preprocess a source file
helikopter-src/hal/HAL_LIB/udpSensorLib.c.i:
	$(MAKE) -f CMakeFiles/communication.dir/build.make CMakeFiles/communication.dir/helikopter-src/hal/HAL_LIB/udpSensorLib.c.i
.PHONY : helikopter-src/hal/HAL_LIB/udpSensorLib.c.i

helikopter-src/hal/HAL_LIB/udpSensorLib.s: helikopter-src/hal/HAL_LIB/udpSensorLib.c.s

.PHONY : helikopter-src/hal/HAL_LIB/udpSensorLib.s

# target to generate assembly for a file
helikopter-src/hal/HAL_LIB/udpSensorLib.c.s:
	$(MAKE) -f CMakeFiles/communication.dir/build.make CMakeFiles/communication.dir/helikopter-src/hal/HAL_LIB/udpSensorLib.c.s
.PHONY : helikopter-src/hal/HAL_LIB/udpSensorLib.c.s

helikopter-src/hal/MOTOR/MOTOR.o: helikopter-src/hal/MOTOR/MOTOR.c.o

.PHONY : helikopter-src/hal/MOTOR/MOTOR.o

# target to build an object file
helikopter-src/hal/MOTOR/MOTOR.c.o:
	$(MAKE) -f CMakeFiles/motor.dir/build.make CMakeFiles/motor.dir/helikopter-src/hal/MOTOR/MOTOR.c.o
.PHONY : helikopter-src/hal/MOTOR/MOTOR.c.o

helikopter-src/hal/MOTOR/MOTOR.i: helikopter-src/hal/MOTOR/MOTOR.c.i

.PHONY : helikopter-src/hal/MOTOR/MOTOR.i

# target to preprocess a source file
helikopter-src/hal/MOTOR/MOTOR.c.i:
	$(MAKE) -f CMakeFiles/motor.dir/build.make CMakeFiles/motor.dir/helikopter-src/hal/MOTOR/MOTOR.c.i
.PHONY : helikopter-src/hal/MOTOR/MOTOR.c.i

helikopter-src/hal/MOTOR/MOTOR.s: helikopter-src/hal/MOTOR/MOTOR.c.s

.PHONY : helikopter-src/hal/MOTOR/MOTOR.s

# target to generate assembly for a file
helikopter-src/hal/MOTOR/MOTOR.c.s:
	$(MAKE) -f CMakeFiles/motor.dir/build.make CMakeFiles/motor.dir/helikopter-src/hal/MOTOR/MOTOR.c.s
.PHONY : helikopter-src/hal/MOTOR/MOTOR.c.s

helikopter-src/hal/SENSOR/GPS.o: helikopter-src/hal/SENSOR/GPS.c.o

.PHONY : helikopter-src/hal/SENSOR/GPS.o

# target to build an object file
helikopter-src/hal/SENSOR/GPS.c.o:
	$(MAKE) -f CMakeFiles/sensor.dir/build.make CMakeFiles/sensor.dir/helikopter-src/hal/SENSOR/GPS.c.o
.PHONY : helikopter-src/hal/SENSOR/GPS.c.o

helikopter-src/hal/SENSOR/GPS.i: helikopter-src/hal/SENSOR/GPS.c.i

.PHONY : helikopter-src/hal/SENSOR/GPS.i

# target to preprocess a source file
helikopter-src/hal/SENSOR/GPS.c.i:
	$(MAKE) -f CMakeFiles/sensor.dir/build.make CMakeFiles/sensor.dir/helikopter-src/hal/SENSOR/GPS.c.i
.PHONY : helikopter-src/hal/SENSOR/GPS.c.i

helikopter-src/hal/SENSOR/GPS.s: helikopter-src/hal/SENSOR/GPS.c.s

.PHONY : helikopter-src/hal/SENSOR/GPS.s

# target to generate assembly for a file
helikopter-src/hal/SENSOR/GPS.c.s:
	$(MAKE) -f CMakeFiles/sensor.dir/build.make CMakeFiles/sensor.dir/helikopter-src/hal/SENSOR/GPS.c.s
.PHONY : helikopter-src/hal/SENSOR/GPS.c.s

helikopter-src/hal/SENSOR/Gyro.o: helikopter-src/hal/SENSOR/Gyro.c.o

.PHONY : helikopter-src/hal/SENSOR/Gyro.o

# target to build an object file
helikopter-src/hal/SENSOR/Gyro.c.o:
	$(MAKE) -f CMakeFiles/sensor.dir/build.make CMakeFiles/sensor.dir/helikopter-src/hal/SENSOR/Gyro.c.o
.PHONY : helikopter-src/hal/SENSOR/Gyro.c.o

helikopter-src/hal/SENSOR/Gyro.i: helikopter-src/hal/SENSOR/Gyro.c.i

.PHONY : helikopter-src/hal/SENSOR/Gyro.i

# target to preprocess a source file
helikopter-src/hal/SENSOR/Gyro.c.i:
	$(MAKE) -f CMakeFiles/sensor.dir/build.make CMakeFiles/sensor.dir/helikopter-src/hal/SENSOR/Gyro.c.i
.PHONY : helikopter-src/hal/SENSOR/Gyro.c.i

helikopter-src/hal/SENSOR/Gyro.s: helikopter-src/hal/SENSOR/Gyro.c.s

.PHONY : helikopter-src/hal/SENSOR/Gyro.s

# target to generate assembly for a file
helikopter-src/hal/SENSOR/Gyro.c.s:
	$(MAKE) -f CMakeFiles/sensor.dir/build.make CMakeFiles/sensor.dir/helikopter-src/hal/SENSOR/Gyro.c.s
.PHONY : helikopter-src/hal/SENSOR/Gyro.c.s

helikopter-src/hal/SENSOR/LIDAR.o: helikopter-src/hal/SENSOR/LIDAR.c.o

.PHONY : helikopter-src/hal/SENSOR/LIDAR.o

# target to build an object file
helikopter-src/hal/SENSOR/LIDAR.c.o:
	$(MAKE) -f CMakeFiles/sensor.dir/build.make CMakeFiles/sensor.dir/helikopter-src/hal/SENSOR/LIDAR.c.o
.PHONY : helikopter-src/hal/SENSOR/LIDAR.c.o

helikopter-src/hal/SENSOR/LIDAR.i: helikopter-src/hal/SENSOR/LIDAR.c.i

.PHONY : helikopter-src/hal/SENSOR/LIDAR.i

# target to preprocess a source file
helikopter-src/hal/SENSOR/LIDAR.c.i:
	$(MAKE) -f CMakeFiles/sensor.dir/build.make CMakeFiles/sensor.dir/helikopter-src/hal/SENSOR/LIDAR.c.i
.PHONY : helikopter-src/hal/SENSOR/LIDAR.c.i

helikopter-src/hal/SENSOR/LIDAR.s: helikopter-src/hal/SENSOR/LIDAR.c.s

.PHONY : helikopter-src/hal/SENSOR/LIDAR.s

# target to generate assembly for a file
helikopter-src/hal/SENSOR/LIDAR.c.s:
	$(MAKE) -f CMakeFiles/sensor.dir/build.make CMakeFiles/sensor.dir/helikopter-src/hal/SENSOR/LIDAR.c.s
.PHONY : helikopter-src/hal/SENSOR/LIDAR.c.s

helikopter-src/hal/SENSOR/Sensor_Lib.o: helikopter-src/hal/SENSOR/Sensor_Lib.c.o

.PHONY : helikopter-src/hal/SENSOR/Sensor_Lib.o

# target to build an object file
helikopter-src/hal/SENSOR/Sensor_Lib.c.o:
	$(MAKE) -f CMakeFiles/sensor.dir/build.make CMakeFiles/sensor.dir/helikopter-src/hal/SENSOR/Sensor_Lib.c.o
.PHONY : helikopter-src/hal/SENSOR/Sensor_Lib.c.o

helikopter-src/hal/SENSOR/Sensor_Lib.i: helikopter-src/hal/SENSOR/Sensor_Lib.c.i

.PHONY : helikopter-src/hal/SENSOR/Sensor_Lib.i

# target to preprocess a source file
helikopter-src/hal/SENSOR/Sensor_Lib.c.i:
	$(MAKE) -f CMakeFiles/sensor.dir/build.make CMakeFiles/sensor.dir/helikopter-src/hal/SENSOR/Sensor_Lib.c.i
.PHONY : helikopter-src/hal/SENSOR/Sensor_Lib.c.i

helikopter-src/hal/SENSOR/Sensor_Lib.s: helikopter-src/hal/SENSOR/Sensor_Lib.c.s

.PHONY : helikopter-src/hal/SENSOR/Sensor_Lib.s

# target to generate assembly for a file
helikopter-src/hal/SENSOR/Sensor_Lib.c.s:
	$(MAKE) -f CMakeFiles/sensor.dir/build.make CMakeFiles/sensor.dir/helikopter-src/hal/SENSOR/Sensor_Lib.c.s
.PHONY : helikopter-src/hal/SENSOR/Sensor_Lib.c.s

helikopter-src/hal/SENSOR/accMag.o: helikopter-src/hal/SENSOR/accMag.c.o

.PHONY : helikopter-src/hal/SENSOR/accMag.o

# target to build an object file
helikopter-src/hal/SENSOR/accMag.c.o:
	$(MAKE) -f CMakeFiles/sensor.dir/build.make CMakeFiles/sensor.dir/helikopter-src/hal/SENSOR/accMag.c.o
.PHONY : helikopter-src/hal/SENSOR/accMag.c.o

helikopter-src/hal/SENSOR/accMag.i: helikopter-src/hal/SENSOR/accMag.c.i

.PHONY : helikopter-src/hal/SENSOR/accMag.i

# target to preprocess a source file
helikopter-src/hal/SENSOR/accMag.c.i:
	$(MAKE) -f CMakeFiles/sensor.dir/build.make CMakeFiles/sensor.dir/helikopter-src/hal/SENSOR/accMag.c.i
.PHONY : helikopter-src/hal/SENSOR/accMag.c.i

helikopter-src/hal/SENSOR/accMag.s: helikopter-src/hal/SENSOR/accMag.c.s

.PHONY : helikopter-src/hal/SENSOR/accMag.s

# target to generate assembly for a file
helikopter-src/hal/SENSOR/accMag.c.s:
	$(MAKE) -f CMakeFiles/sensor.dir/build.make CMakeFiles/sensor.dir/helikopter-src/hal/SENSOR/accMag.c.s
.PHONY : helikopter-src/hal/SENSOR/accMag.c.s

helikopter-src/hal/SENSOR/barometer.o: helikopter-src/hal/SENSOR/barometer.c.o

.PHONY : helikopter-src/hal/SENSOR/barometer.o

# target to build an object file
helikopter-src/hal/SENSOR/barometer.c.o:
	$(MAKE) -f CMakeFiles/sensor.dir/build.make CMakeFiles/sensor.dir/helikopter-src/hal/SENSOR/barometer.c.o
.PHONY : helikopter-src/hal/SENSOR/barometer.c.o

helikopter-src/hal/SENSOR/barometer.i: helikopter-src/hal/SENSOR/barometer.c.i

.PHONY : helikopter-src/hal/SENSOR/barometer.i

# target to preprocess a source file
helikopter-src/hal/SENSOR/barometer.c.i:
	$(MAKE) -f CMakeFiles/sensor.dir/build.make CMakeFiles/sensor.dir/helikopter-src/hal/SENSOR/barometer.c.i
.PHONY : helikopter-src/hal/SENSOR/barometer.c.i

helikopter-src/hal/SENSOR/barometer.s: helikopter-src/hal/SENSOR/barometer.c.s

.PHONY : helikopter-src/hal/SENSOR/barometer.s

# target to generate assembly for a file
helikopter-src/hal/SENSOR/barometer.c.s:
	$(MAKE) -f CMakeFiles/sensor.dir/build.make CMakeFiles/sensor.dir/helikopter-src/hal/SENSOR/barometer.c.s
.PHONY : helikopter-src/hal/SENSOR/barometer.c.s

helikopter-src/hal/SENSOR/batteryCheck.o: helikopter-src/hal/SENSOR/batteryCheck.c.o

.PHONY : helikopter-src/hal/SENSOR/batteryCheck.o

# target to build an object file
helikopter-src/hal/SENSOR/batteryCheck.c.o:
	$(MAKE) -f CMakeFiles/sensor.dir/build.make CMakeFiles/sensor.dir/helikopter-src/hal/SENSOR/batteryCheck.c.o
.PHONY : helikopter-src/hal/SENSOR/batteryCheck.c.o

helikopter-src/hal/SENSOR/batteryCheck.i: helikopter-src/hal/SENSOR/batteryCheck.c.i

.PHONY : helikopter-src/hal/SENSOR/batteryCheck.i

# target to preprocess a source file
helikopter-src/hal/SENSOR/batteryCheck.c.i:
	$(MAKE) -f CMakeFiles/sensor.dir/build.make CMakeFiles/sensor.dir/helikopter-src/hal/SENSOR/batteryCheck.c.i
.PHONY : helikopter-src/hal/SENSOR/batteryCheck.c.i

helikopter-src/hal/SENSOR/batteryCheck.s: helikopter-src/hal/SENSOR/batteryCheck.c.s

.PHONY : helikopter-src/hal/SENSOR/batteryCheck.s

# target to generate assembly for a file
helikopter-src/hal/SENSOR/batteryCheck.c.s:
	$(MAKE) -f CMakeFiles/sensor.dir/build.make CMakeFiles/sensor.dir/helikopter-src/hal/SENSOR/batteryCheck.c.s
.PHONY : helikopter-src/hal/SENSOR/batteryCheck.c.s

helikopter-src/hal/SENSOR/imu.o: helikopter-src/hal/SENSOR/imu.c.o

.PHONY : helikopter-src/hal/SENSOR/imu.o

# target to build an object file
helikopter-src/hal/SENSOR/imu.c.o:
	$(MAKE) -f CMakeFiles/sensor.dir/build.make CMakeFiles/sensor.dir/helikopter-src/hal/SENSOR/imu.c.o
.PHONY : helikopter-src/hal/SENSOR/imu.c.o

helikopter-src/hal/SENSOR/imu.i: helikopter-src/hal/SENSOR/imu.c.i

.PHONY : helikopter-src/hal/SENSOR/imu.i

# target to preprocess a source file
helikopter-src/hal/SENSOR/imu.c.i:
	$(MAKE) -f CMakeFiles/sensor.dir/build.make CMakeFiles/sensor.dir/helikopter-src/hal/SENSOR/imu.c.i
.PHONY : helikopter-src/hal/SENSOR/imu.c.i

helikopter-src/hal/SENSOR/imu.s: helikopter-src/hal/SENSOR/imu.c.s

.PHONY : helikopter-src/hal/SENSOR/imu.s

# target to generate assembly for a file
helikopter-src/hal/SENSOR/imu.c.s:
	$(MAKE) -f CMakeFiles/sensor.dir/build.make CMakeFiles/sensor.dir/helikopter-src/hal/SENSOR/imu.c.s
.PHONY : helikopter-src/hal/SENSOR/imu.c.s

helikopter-src/lld/LLD_I2C.o: helikopter-src/lld/LLD_I2C.c.o

.PHONY : helikopter-src/lld/LLD_I2C.o

# target to build an object file
helikopter-src/lld/LLD_I2C.c.o:
	$(MAKE) -f CMakeFiles/lld.dir/build.make CMakeFiles/lld.dir/helikopter-src/lld/LLD_I2C.c.o
.PHONY : helikopter-src/lld/LLD_I2C.c.o

helikopter-src/lld/LLD_I2C.i: helikopter-src/lld/LLD_I2C.c.i

.PHONY : helikopter-src/lld/LLD_I2C.i

# target to preprocess a source file
helikopter-src/lld/LLD_I2C.c.i:
	$(MAKE) -f CMakeFiles/lld.dir/build.make CMakeFiles/lld.dir/helikopter-src/lld/LLD_I2C.c.i
.PHONY : helikopter-src/lld/LLD_I2C.c.i

helikopter-src/lld/LLD_I2C.s: helikopter-src/lld/LLD_I2C.c.s

.PHONY : helikopter-src/lld/LLD_I2C.s

# target to generate assembly for a file
helikopter-src/lld/LLD_I2C.c.s:
	$(MAKE) -f CMakeFiles/lld.dir/build.make CMakeFiles/lld.dir/helikopter-src/lld/LLD_I2C.c.s
.PHONY : helikopter-src/lld/LLD_I2C.c.s

helikopter-src/lld/LLD_UART.o: helikopter-src/lld/LLD_UART.c.o

.PHONY : helikopter-src/lld/LLD_UART.o

# target to build an object file
helikopter-src/lld/LLD_UART.c.o:
	$(MAKE) -f CMakeFiles/lld.dir/build.make CMakeFiles/lld.dir/helikopter-src/lld/LLD_UART.c.o
.PHONY : helikopter-src/lld/LLD_UART.c.o

helikopter-src/lld/LLD_UART.i: helikopter-src/lld/LLD_UART.c.i

.PHONY : helikopter-src/lld/LLD_UART.i

# target to preprocess a source file
helikopter-src/lld/LLD_UART.c.i:
	$(MAKE) -f CMakeFiles/lld.dir/build.make CMakeFiles/lld.dir/helikopter-src/lld/LLD_UART.c.i
.PHONY : helikopter-src/lld/LLD_UART.c.i

helikopter-src/lld/LLD_UART.s: helikopter-src/lld/LLD_UART.c.s

.PHONY : helikopter-src/lld/LLD_UART.s

# target to generate assembly for a file
helikopter-src/lld/LLD_UART.c.s:
	$(MAKE) -f CMakeFiles/lld.dir/build.make CMakeFiles/lld.dir/helikopter-src/lld/LLD_UART.c.s
.PHONY : helikopter-src/lld/LLD_UART.c.s

helikopter-src/main/main.o: helikopter-src/main/main.c.o

.PHONY : helikopter-src/main/main.o

# target to build an object file
helikopter-src/main/main.c.o:
	$(MAKE) -f CMakeFiles/HELIKOPTER.dir/build.make CMakeFiles/HELIKOPTER.dir/helikopter-src/main/main.c.o
.PHONY : helikopter-src/main/main.c.o

helikopter-src/main/main.i: helikopter-src/main/main.c.i

.PHONY : helikopter-src/main/main.i

# target to preprocess a source file
helikopter-src/main/main.c.i:
	$(MAKE) -f CMakeFiles/HELIKOPTER.dir/build.make CMakeFiles/HELIKOPTER.dir/helikopter-src/main/main.c.i
.PHONY : helikopter-src/main/main.c.i

helikopter-src/main/main.s: helikopter-src/main/main.c.s

.PHONY : helikopter-src/main/main.s

# target to generate assembly for a file
helikopter-src/main/main.c.s:
	$(MAKE) -f CMakeFiles/HELIKOPTER.dir/build.make CMakeFiles/HELIKOPTER.dir/helikopter-src/main/main.c.s
.PHONY : helikopter-src/main/main.c.s

helikopter-src/sig/ImuFilter.o: helikopter-src/sig/ImuFilter.c.o

.PHONY : helikopter-src/sig/ImuFilter.o

# target to build an object file
helikopter-src/sig/ImuFilter.c.o:
	$(MAKE) -f CMakeFiles/sig.dir/build.make CMakeFiles/sig.dir/helikopter-src/sig/ImuFilter.c.o
.PHONY : helikopter-src/sig/ImuFilter.c.o

helikopter-src/sig/ImuFilter.i: helikopter-src/sig/ImuFilter.c.i

.PHONY : helikopter-src/sig/ImuFilter.i

# target to preprocess a source file
helikopter-src/sig/ImuFilter.c.i:
	$(MAKE) -f CMakeFiles/sig.dir/build.make CMakeFiles/sig.dir/helikopter-src/sig/ImuFilter.c.i
.PHONY : helikopter-src/sig/ImuFilter.c.i

helikopter-src/sig/ImuFilter.s: helikopter-src/sig/ImuFilter.c.s

.PHONY : helikopter-src/sig/ImuFilter.s

# target to generate assembly for a file
helikopter-src/sig/ImuFilter.c.s:
	$(MAKE) -f CMakeFiles/sig.dir/build.make CMakeFiles/sig.dir/helikopter-src/sig/ImuFilter.c.s
.PHONY : helikopter-src/sig/ImuFilter.c.s

helikopter-src/sig/Orientation.o: helikopter-src/sig/Orientation.c.o

.PHONY : helikopter-src/sig/Orientation.o

# target to build an object file
helikopter-src/sig/Orientation.c.o:
	$(MAKE) -f CMakeFiles/sig.dir/build.make CMakeFiles/sig.dir/helikopter-src/sig/Orientation.c.o
.PHONY : helikopter-src/sig/Orientation.c.o

helikopter-src/sig/Orientation.i: helikopter-src/sig/Orientation.c.i

.PHONY : helikopter-src/sig/Orientation.i

# target to preprocess a source file
helikopter-src/sig/Orientation.c.i:
	$(MAKE) -f CMakeFiles/sig.dir/build.make CMakeFiles/sig.dir/helikopter-src/sig/Orientation.c.i
.PHONY : helikopter-src/sig/Orientation.c.i

helikopter-src/sig/Orientation.s: helikopter-src/sig/Orientation.c.s

.PHONY : helikopter-src/sig/Orientation.s

# target to generate assembly for a file
helikopter-src/sig/Orientation.c.s:
	$(MAKE) -f CMakeFiles/sig.dir/build.make CMakeFiles/sig.dir/helikopter-src/sig/Orientation.c.s
.PHONY : helikopter-src/sig/Orientation.c.s

helikopter-src/sig/matrixLib.o: helikopter-src/sig/matrixLib.c.o

.PHONY : helikopter-src/sig/matrixLib.o

# target to build an object file
helikopter-src/sig/matrixLib.c.o:
	$(MAKE) -f CMakeFiles/sig.dir/build.make CMakeFiles/sig.dir/helikopter-src/sig/matrixLib.c.o
.PHONY : helikopter-src/sig/matrixLib.c.o

helikopter-src/sig/matrixLib.i: helikopter-src/sig/matrixLib.c.i

.PHONY : helikopter-src/sig/matrixLib.i

# target to preprocess a source file
helikopter-src/sig/matrixLib.c.i:
	$(MAKE) -f CMakeFiles/sig.dir/build.make CMakeFiles/sig.dir/helikopter-src/sig/matrixLib.c.i
.PHONY : helikopter-src/sig/matrixLib.c.i

helikopter-src/sig/matrixLib.s: helikopter-src/sig/matrixLib.c.s

.PHONY : helikopter-src/sig/matrixLib.s

# target to generate assembly for a file
helikopter-src/sig/matrixLib.c.s:
	$(MAKE) -f CMakeFiles/sig.dir/build.make CMakeFiles/sig.dir/helikopter-src/sig/matrixLib.c.s
.PHONY : helikopter-src/sig/matrixLib.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... HELIKOPTER"
	@echo "... communication"
	@echo "... sensor"
	@echo "... motor"
	@echo "... lld"
	@echo "... sig"
	@echo "... helikopter-src/hal/HAL_LIB/GPIO.o"
	@echo "... helikopter-src/hal/HAL_LIB/GPIO.i"
	@echo "... helikopter-src/hal/HAL_LIB/GPIO.s"
	@echo "... helikopter-src/hal/HAL_LIB/HAL_ADC.o"
	@echo "... helikopter-src/hal/HAL_LIB/HAL_ADC.i"
	@echo "... helikopter-src/hal/HAL_LIB/HAL_ADC.s"
	@echo "... helikopter-src/hal/HAL_LIB/udpLib.o"
	@echo "... helikopter-src/hal/HAL_LIB/udpLib.i"
	@echo "... helikopter-src/hal/HAL_LIB/udpLib.s"
	@echo "... helikopter-src/hal/HAL_LIB/udpSensorLib.o"
	@echo "... helikopter-src/hal/HAL_LIB/udpSensorLib.i"
	@echo "... helikopter-src/hal/HAL_LIB/udpSensorLib.s"
	@echo "... helikopter-src/hal/MOTOR/MOTOR.o"
	@echo "... helikopter-src/hal/MOTOR/MOTOR.i"
	@echo "... helikopter-src/hal/MOTOR/MOTOR.s"
	@echo "... helikopter-src/hal/SENSOR/GPS.o"
	@echo "... helikopter-src/hal/SENSOR/GPS.i"
	@echo "... helikopter-src/hal/SENSOR/GPS.s"
	@echo "... helikopter-src/hal/SENSOR/Gyro.o"
	@echo "... helikopter-src/hal/SENSOR/Gyro.i"
	@echo "... helikopter-src/hal/SENSOR/Gyro.s"
	@echo "... helikopter-src/hal/SENSOR/LIDAR.o"
	@echo "... helikopter-src/hal/SENSOR/LIDAR.i"
	@echo "... helikopter-src/hal/SENSOR/LIDAR.s"
	@echo "... helikopter-src/hal/SENSOR/Sensor_Lib.o"
	@echo "... helikopter-src/hal/SENSOR/Sensor_Lib.i"
	@echo "... helikopter-src/hal/SENSOR/Sensor_Lib.s"
	@echo "... helikopter-src/hal/SENSOR/accMag.o"
	@echo "... helikopter-src/hal/SENSOR/accMag.i"
	@echo "... helikopter-src/hal/SENSOR/accMag.s"
	@echo "... helikopter-src/hal/SENSOR/barometer.o"
	@echo "... helikopter-src/hal/SENSOR/barometer.i"
	@echo "... helikopter-src/hal/SENSOR/barometer.s"
	@echo "... helikopter-src/hal/SENSOR/batteryCheck.o"
	@echo "... helikopter-src/hal/SENSOR/batteryCheck.i"
	@echo "... helikopter-src/hal/SENSOR/batteryCheck.s"
	@echo "... helikopter-src/hal/SENSOR/imu.o"
	@echo "... helikopter-src/hal/SENSOR/imu.i"
	@echo "... helikopter-src/hal/SENSOR/imu.s"
	@echo "... helikopter-src/lld/LLD_I2C.o"
	@echo "... helikopter-src/lld/LLD_I2C.i"
	@echo "... helikopter-src/lld/LLD_I2C.s"
	@echo "... helikopter-src/lld/LLD_UART.o"
	@echo "... helikopter-src/lld/LLD_UART.i"
	@echo "... helikopter-src/lld/LLD_UART.s"
	@echo "... helikopter-src/main/main.o"
	@echo "... helikopter-src/main/main.i"
	@echo "... helikopter-src/main/main.s"
	@echo "... helikopter-src/sig/ImuFilter.o"
	@echo "... helikopter-src/sig/ImuFilter.i"
	@echo "... helikopter-src/sig/ImuFilter.s"
	@echo "... helikopter-src/sig/Orientation.o"
	@echo "... helikopter-src/sig/Orientation.i"
	@echo "... helikopter-src/sig/Orientation.s"
	@echo "... helikopter-src/sig/matrixLib.o"
	@echo "... helikopter-src/sig/matrixLib.i"
	@echo "... helikopter-src/sig/matrixLib.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

