all:ADC BATTERY GPS IMU LASER LLD_IF MAIN

ADC:FORCE
	cd ADC; make all

BATTERY:FORCE
	cd BATTERY; make all

GPS:FORCE
	cd GPS; make all

IMU:FORCE
	cd IMU; make all

LASER:FORCE
	cd LASER; make all

LLD_IF:FORCE
	cd LLD_IF; make all

MAIN:FORCE
	cd MAIN; make all

FORCE:

clean:
	cd ADC; make clean
	cd BATTERY; make clean
	cd GPS; make clean
	cd IMU; make clean
	cd LASER; make clean
	cd LLD_IF; make clean
	cd MAIN; make clean
