/*
  *
  *   --- THIS FILE GENERATED BY S-FUNCTION BUILDER: 3.0 ---
  *
  *   This file is a wrapper S-function produced by the S-Function
  *   Builder which only recognizes certain fields.  Changes made
  *   outside these fields will be lost the next time the block is
  *   used to load, edit, and resave this file. This file will be overwritten
  *   by the S-function Builder block. If you want to edit this file by hand, 
  *   you must change it only in the area defined as:  
  *
  *        %%%-SFUNWIZ_wrapper_XXXXX_Changes_BEGIN 
  *            Your Changes go here
  *        %%%-SFUNWIZ_wrapper_XXXXXX_Changes_END
  *
  *   For better compatibility with the Simulink Coder, the
  *   "wrapper" S-function technique is used.  This is discussed
  *   in the Simulink Coder User's Manual in the Chapter titled,
  *   "Wrapper S-functions".
  *
  *   Created: Sat Jun 27 16:27:07 2015
  */


/*
 * Include Files
 *
 */
#if defined(MATLAB_MEX_FILE)
#include "tmwtypes.h"
#include "simstruc_types.h"
#else
#include "rtwtypes.h"
#endif

/* %%%-SFUNWIZ_wrapper_includes_Changes_BEGIN --- EDIT HERE TO _END */
#include <math.h>
#include "path to udpImuLib.h"
/* %%%-SFUNWIZ_wrapper_includes_Changes_END --- EDIT HERE TO _BEGIN */
#define u_width 
#define y_width 1
/*
 * Create external references here.  
 *
 */
/* %%%-SFUNWIZ_wrapper_externs_Changes_BEGIN --- EDIT HERE TO _END */
/* extern double func(double a); */
/* %%%-SFUNWIZ_wrapper_externs_Changes_END --- EDIT HERE TO _BEGIN */

/*
 * Output functions
 *
 */
void myUdpSource_Outputs_wrapper(real_T *acc,
                                 real_T *gyro,
                                 real_T *mag,
                                 real_T *baro,
                                 real_T *temp, 
                                 const real_T  *sampleTime, 
                                 const int_T p_width0,
                                 int socketNum)
{
/* %%%-SFUNWIZ_wrapper_Outputs_Changes_BEGIN --- EDIT HERE TO _END */
	
		// define payload structure of UDP packets
    halMatlab_rtImuPayload l_udpPayload_st;
    
		// get a new packet
    l_udpPayload_st = g_halMatlab_recvImuState_bool( socketNum );
    
		// print remote system time for debugging purposes here
    printf("Remote time: %ld.%ld\n",
						l_udpPayload_st.timestamp_st.tv_sec,
						l_udpPayload_st.timestamp_st.tv_nsec);
    
		/* translate the UDP packet data to simulink signals
		 * Remark: Since all used data of the UDP packets are
		 *         already of the type double (see f64 postfix)
		 *         the data is already matching the double
		 *         type data representation, used by MATLAB
		 *         internally.
		 */
    acc[0] = l_udpPayload_st.imuState_st.acc.x_f64;
    acc[1] = l_udpPayload_st.imuState_st.acc.y_f64;
    acc[2] = l_udpPayload_st.imuState_st.acc.z_f64;
    
    gyro[0] = l_udpPayload_st.imuState_st.gyro.l_roll_f64;
    gyro[1] = l_udpPayload_st.imuState_st.gyro.l_pitch_f64;
    gyro[2] = l_udpPayload_st.imuState_st.gyro.l_yaw_f64;
    
    mag[0] = l_udpPayload_st.imuState_st.mag.x_f64;
    mag[1] = l_udpPayload_st.imuState_st.mag.y_f64;
    mag[2] = l_udpPayload_st.imuState_st.mag.z_f64;
    
    baro[0] = l_udpPayload_st.imuState_st.pressure_f64;
    
    temp[0] = l_udpPayload_st.imuState_st.temperature_f64;
/* %%%-SFUNWIZ_wrapper_Outputs_Changes_END --- EDIT HERE TO _BEGIN */
}
/* %%%-SFUNWIZ_wrapper_Outputs_Changes_BEGIN --- EDIT HERE TO _END */
/* This sample sets the output equal to the input
      y0[0] = u0[0]; 
 For complex signals use: y0[0].re = u0[0].re; 
      y0[0].im = u0[0].im;
      y1[0].re = u1[0].re;
      y1[0].im = u1[0].im;
*/
/* %%%-SFUNWIZ_wrapper_Outputs_Changes_END --- EDIT HERE TO _BEGIN */
